#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         2
bspc config window_gap            6

bspc config focused_border_color	"#ff0000"
#bspc config focused_border_width 1

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#background
feh --no-fehbg --bg-fill /home/jzambrano/Imagenes/fondo3.png

#Polybar
bash ~/.config/polybar/launch.sh --hack

#picom
picom --experimental-backends &

bspc config border_width 0

xsetroot -cursor_name left_ptr &
flameshot &

#vm-ware
vmware-user-suid-wrapper
