#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#Monitor
xrandr --output "eDP" --auto --output "HDMI-1-0" --left-of "eDP"

pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

bspc monitor HDMI-1-0 -d I II III IV V VI VII VII IX X
#bspc monitor eDP -d I II III IV V VI VII VII IX X

#bspc config border_width         2
bspc config window_gap            6

#bspc config focused_border_color	"#e69875"
#bspc config focused_border_width 1

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#background
feh --no-fehbg --bg-fill /home/zxmbrxnx/Escritorio/fondos/fondo2.jpg

#Polybar
bash ~/.config/polybar/launch.sh --zxmbrxnx
#bash ~/.config/polybar/neon/launch.sh
#picom
picom --experimental-backends &

bspc config border_width 0

xsetroot -cursor_name left_ptr &
flameshot &
copyq &

#bspc wm -r

#Active hostpot

#nmcli connection up Hotspot &
ufw disable
#vm-ware
#vmware-user-suid-wrapper
